dict = {
'South Carolina' : ['charleston', 'columbia', 'florence', 'greenville', 'hiltonhead', 'myrtlebeach'],
'Rhode Island' : ['providence'],
'New Mexico' : ['santafe', 'roswell', 'lascruces', 'farmington', 'clovis', 'albuquerque'],
'Alabama' : ['auburn', 'bham', 'dothan', 'shoals', 'gadsden', 'huntsville', 'mobile', 'montgomery', 'tuscaloosa'],
'Florida' : ['daytona', 'keys', 'fortlauderdale', 'fortmyers', 'gainesville', 'cfl', 'jacksonville', 'lakeland', 'lakecity', 'ocala', 'okaloosa', 'orlando', 'panamacity', 'pensacola', 'sarasota', 'miami', 'spacecoast', 'staugustine', 'tallahassee', 'tampa', 'treasure', 'westpalmbeach'],
'California' : ['bakersfield', 'chico', 'fresno', 'goldcountry', 'hanford', 'humboldt', 'imperial', 'inlandempire', 'losangeles', 'mendocino', 'merced', 'modesto', 'monterey', 'orangecounty', 'palmsprings', 'redding', 'sacramento', 'sandiego', 'sfbay', 'slo', 'santabarbara', 'santamaria', 'siskiyou', 'stockton', 'susanville', 'ventura', 'visalia', 'yubasutter'],
'New Hampshire' : ['nh'],
'Massachusetts' : ['boston', 'capecod', 'southcoast', 'westernmass', 'worcester'],
'Tennessee' : ['chattanooga', 'clarksville', 'cookeville', 'jacksontn', 'knoxville', 'memphis', 'nashville', 'tricities'],
'Maryland' : ['annapolis', 'baltimore', 'easternshore', 'frederick', 'smd', 'westmd'],
'Louisiana' : ['batonrouge', 'cenla', 'houma', 'lafayette', 'lakecharles', 'monroe', 'neworleans', 'shreveport'],
'Ohio' : ['akroncanton', 'ashtabula', 'athensohio', 'chillicothe', 'cincinnati', 'cleveland', 'columbus', 'dayton', 'limaohio', 'mansfield', 'sandusky', 'toledo', 'tuscarawas', 'youngstown', 'zanesville'],
'West Virginia' : ['charleston', 'martinsburg', 'huntington', 'morgantown', 'wheeling', 'parkersburg', 'swv', 'wv'],
'Idaho' : ['boise', 'eastidaho', 'lewiston', 'twinfalls'],
'Virginia' : ['charlottesville', 'danville', 'fredericksburg', 'norfolk', 'harrisonburg', 'lynchburg', 'blacksburg', 'richmond', 'roanoke', 'swva', 'winchester'],
'Mississippi' : ['gulfport', 'hattiesburg', 'jackson', 'meridian', 'northmiss', 'natchez'],
'Texas' : ['wichitafalls', 'waco', 'victoriatx', 'easttexas', 'texoma', 'bigbend', 'sanmarcos', 'sanantonio', 'sanangelo', 'odessa', 'mcallen', 'lubbock', 'laredo', 'killeen', 'houston', 'galveston', 'elpaso', 'delrio', 'nacogdoches', 'dallas', 'corpuschristi', 'abilene', 'amarillo', 'austin', 'beaumont', 'brownsville', 'collegestation'],
'Vermont' : ['vermont'],
'Wyoming' : ['wyoming'],
'New York' : ['albany', 'binghamton', 'buffalo', 'catskills', 'chautauqua', 'elmira', 'fingerlakes', 'glensfalls', 'hudsonvalley', 'ithaca', 'longisland', 'newyork', 'oneonta', 'plattsburgh', 'potsdam', 'rochester', 'syracuse', 'twintiers', 'utica', 'watertown'],
'Kansas' : ['lawrence', 'ksu', 'nwks', 'salina', 'seks', 'swks', 'topeka', 'wichita'],
'New Jersey' : ['cnj', 'jerseyshore', 'newjersey', 'southjersey'],
'Michigan' : ['annarbor', 'battlecreek', 'centralmich', 'detroit', 'flint', 'grandrapids', 'holland', 'jxn', 'kalamazoo', 'lansing', 'monroe', 'muskegon', 'nmi', 'porthuron', 'saginaw', 'swmi', 'thumb', 'up'],
'Maine' : ['maine'],
'Colorado' : ['boulder', 'cosprings', 'denver', 'eastco', 'fortcollins', 'rockies', 'pueblo', 'westslope'],
'Pennsylvania' : ['altoona', 'chambersburg', 'erie', 'harrisburg', 'lancaster', 'allentown', 'meadville', 'philadelphia', 'pittsburgh', 'poconos', 'reading', 'scranton', 'pennstate', 'williamsport', 'york'],
'Arkansas' : ['fayar', 'fortsmith', 'jonesboro', 'littlerock', 'texarkana'],
'Missouri' : ['columbiamo', 'joplin', 'kansascity', 'kirksville', 'loz', 'semo', 'springfield', 'stjoseph', 'stlouis'],
'Iowa' : ['ames', 'cedarrapids', 'desmoines', 'dubuque', 'fortdodge', 'masoncity', 'iowacity', 'quadcities', 'siouxcity', 'waterloo', 'ottumwa'],
'Territories' : ['virgin', 'puertorico', 'micronesia'],
'North Dakota' : ['bismarck', 'fargo', 'grandforks', 'nd'],
'Oregon' : ['bend', 'corvallis', 'eastoregon', 'eugene', 'klamath', 'medford', 'oregoncoast', 'portland', 'roseburg', 'salem'],
'Indiana' : ['bloomington', 'evansville', 'fortwayne', 'indianapolis', 'kokomo', 'muncie', 'richmondin', 'tippecanoe', 'southbend', 'terrehaute'],
'Wisconsin' : ['appleton', 'eauclaire', 'greenbay', 'janesville', 'racine', 'lacrosse', 'madison', 'milwaukee', 'northernwi', 'sheboygan', 'wausau'],
'Nevada' : ['elko', 'lasvegas', 'reno'],
'Minnesota' : ['bemidji', 'brainerd', 'duluth', 'mankato', 'minneapolis', 'rmn', 'marshall', 'stcloud'],
'Delaware' : ['Delaware'],
'Washington' : ['bellingham', 'kpr', 'moseslake', 'olympic', 'pullman', 'seattle', 'skagit', 'spokane', 'wenatchee', 'yakima'],
'Illinois' : ['bn', 'chambana', 'chicago', 'decatur', 'lasalle', 'carbondale', 'mattoon', 'peoria', 'rockford', 'springfieldil', 'quincy'],
'Hawaii' : ['honolulu'],
'Connecticut' : ['newlondon', 'hartford', 'newhaven', 'nwct'],
'Montana' : ['billings', 'bozeman', 'butte', 'greatfalls', 'helena', 'kalispell', 'missoula', 'montana'],
'District of Columbia' : ['washingtondc'],
'Oklahoma' : ['lawton', 'enid', 'oklahomacity', 'stillwater', 'tulsa'],
'Arizona' : ['flagstaff', 'mohave', 'phoenix', 'prescott', 'showlow', 'sierravista', 'tucson', 'yuma'],
'North Carolina' : ['asheville', 'boone', 'charlotte', 'eastnc', 'fayetteville', 'greensboro', 'hickory', 'onslow', 'outerbanks', 'raleigh', 'wilmington', 'winstonsalem'],
'Kentucky' : ['louisville', 'lexington', 'owensboro', 'westky', 'eastky', 'bgky'],
'Alaska' : ['anchorage', 'fairbanks', 'kenai', 'juneau'],
'Utah' : ['logan', 'ogden', 'provo', 'saltlakecity', 'stgeorge'],
'Georgia' : ['albany', 'athensga', 'atlanta', 'augusta', 'brunswick', 'columbusga', 'macon', 'nwga', 'savannah', 'valdosta'],
'Nebraska' : ['grandisland', 'lincoln', 'northplatte', 'omaha', 'scottsbluff'],
'South Dakota' : ['sd', 'rapidcity', 'nesd', 'csd', 'siouxfalls'],
}
def get_state(state):
    return (dict[state])
